# Etapa base: imagem Python oficial
FROM python:3.11-slim

# Define diretório de trabalho no container
WORKDIR /app

# Copia os arquivos do projeto para dentro do container
COPY . .

# Instala as dependências do Python
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Expõe a porta usada pelo Sanic
EXPOSE 8000

# Comando para rodar a aplicação Sanic
CMD ["sanic", "app.app", "--host=0.0.0.0", "--port=8000", "--dev"]