version: "3.9"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemonAPP
    ports:
      - "5433:5432"
    networks:
      - app-tier
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: pokemonAPP-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    image: sanic-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/pokemonAPP
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    container_name: pokemonAPP-backend
    networks:
      - app-tier
    env_file:
      - .env

networks:
  app-tier:
    driver: bridge
